### ISSUE TITLE
axis の設定をまとめたい

### ISSUE THREAD

**Issue by mikoto2000** [mikoto2000/embulk-output-chart#1]
```
x_axis_type:
x_axis_name:
x_axis_force_zero_in_range:
```

となっているのを

```
x_axis:
  type:
  name:
  force_zero_in_range:
```

という形にしたい。
